version: '{build}'
image: Visual Studio 2017

# Setup
pull_requests:
  do_not_increment_build_number: true

# Setup build version
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        $env:Build_Version = "$($env:APPVEYOR_REPO_TAG_NAME.Replace('v', ''))";
    }
    else
    {
        $env:Build_Version = "$($env:APPVEYOR_BUILD_VERSION)";
    }

# Installation
install:
  - cmd: ./generateSolution.bat

# Assembly infos & csproj patching
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: '$(Build_Version)'
  assembly_file_version: '$(Build_Version)'
  assembly_informational_version: '$(Build_Version)'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(Build_Version)'
  package_version: '$(Build_Version)'
  assembly_version: '$(Build_Version)'
  file_version: '$(Build_Version)'
  informational_version: '$(Build_Version)'

# Build configurations
platform:
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

# Build
before_build:
  - nuget restore

build:
  verbosity: normal

# Artifact
artifacts:  
  - path: '**\bin\Release\*.nupkg'
    name: NuGet